services:
  ocr:
    build: ./
    command: sleep infinity
    network_mode: host
    restart: unless-stopped
    volumes:
      - ..:/workspace
      - ~/.ssh:/home/node/.ssh
    ports:
      - "5000:5000"
